apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoip.name" . }}
spec:
  selector: {app: {{ include "geoip.name" . }}}
  ports:
  - {name: grpc, port: 9000, targetPort: grpc, appProtocol: kubernetes.io/h2c}
  - {name: admin, port: 8080, targetPort: admin}
